export const faqCategories = [
  {
    id: 'status_guide',
    title: 'Status Guide',
    type: 'section',
    data: [
      {
        id: 'tracking_pr',
        title: 'PR (Purchase Request)',
        statuses: [
          'Encoded',
          'CBO Received',
          'Pending at CBO',
          'Pending Released - CBO',
          'GSO Received',
          'Pending at GSO',
          'Pending Released - GSO',
          'GSO Released',
          'CTO Received',
          'Pending at CTO',
          'Pending Released - CTO',
          'Admin Received',
          'Pending at Admin',
          'Pending Released - Admin',
          'Forwarding to BAC',
          'BAC Received',
          'Pending at BAC',
          'Pending Released - BAC',
          'Pending at Pre-mode Classification - BAC',
          'Pending Released Pre-mode Classification - BAC',
          'For Deliberation - BAC Secretariat',
          'Final Mode Approved - BAC Secretariat',
          'Pending at Final Mode Approved - BAC Secretariat',
          'Pending Released Final Mode Approved - BAC Secretariat',
          'Bid Preparation - BAC Secretariat',
          'For Posting',
          'Bidding Scheduled and Posted',
          'For Canvassing',
          'Drafting Abstract',
          'For Draft Abstract',
          'On Bidding Process',
          'Drafting Abstract',
          'Post Qualification - BAC TWG',
          'Transmitting to BAC TWG',
          'NOA Preparation - BAC Secretariat',
          'For Awarding',
          'NOA Received - Admin',
          'Pending NOA - Admin',
          'Pending Released NOA - Admin',
          'For Final Abstract',
          'NOA for Pick-up - Admin',
          'Released for Final Abstract',
          'Preparation & Result of Public Bidding - BAC Secretariat',
          'For Signature',
          'PR for Pick-up',
          'Final Abstract Signed',
          'For P.O',
        ],
      },
      {
        id: 'tracking_po',
        title: 'PO (Purchase Order)',
        statuses: [
          'Encoded',
          'GSO Received',
          'Pending at GSO',
          'Pending Released - GSO',
          'Admin Received',
          'Pending at Admin',
          'Pending Released - Admin',
          'Serve to Supplier',
          'Supplier Conformed',
          'Fund Control',
          'Pending at CBO',
          'Pending Released - CBO',
          'Waiting for Delivery',
        ],
      },
      {
        id: 'tracking_px',
        title: 'PX (Payment)',
        statuses: [
          'Encoded',
          'For Inspection',
          'Inspection - GSO',
          'Pending Inspection - GSO',
          'Pending Released - Inspection',
          'Inspected',
          'Inventory',
          'Pending at GSO - Inventory',
          'Pending Released - Inventory',
          'CAO Received',
          'Pending at CAO',
          'Pending Released - CAO',
          'On Evaluation - Accounting',
          'Evaluated - Accounting',
          'Forwarding Transmittal',
          'Check Preparation - CTO',
          'Forwarded to Admin - Administration',
          'Check Advised',
          'Check Released',
        ],
      },
      {
        id: 'tracking_py',
        title: 'PY (Vouchers)',
        statuses: [
          'Encoded',
          'Admin Operation Received',
          'Pending at Admin Operation',
          'Pending Released - Admin Operation',
          'CBO Received',
          'Pending at CBO',
          'Pending Released - CBO',
          'CBO Released',
          'CAO Received',
          'Pending at CAO',
          'Pending Released - CAO',
          'Fund Correction',
          'On Evaluation - Accounting',
          'Carded - Accounting',
          'SLP Created - Accounting',
          'Evaluated - Accounting',
          'Forwarding Transmittal',
          'Check Preparation - CTO',
          'Forwarded to Admin - Operation',
          'Forwarded to Admin - Administration',
          'Forwarded to SP - Admin',
          'Check Advised',
          'Check Released',
        ],
      },
    ],
  },
  {
    id: 'general_questions',
    title: 'General Questions',
    type: 'faq',
    data: [
      {
        id: 'how_to_upload',
        question: 'How do I upload a document?',
        answer: 'To upload a document, navigate to the "Documents" tab and tap the "+" icon in the top right corner. Select the document type and follow the prompts to upload your file.',
      },
      {
        id: 'forgot_password',
        question: 'What if I forget my password?',
        answer: 'On the login screen, tap "Forgot Password?" and follow the instructions to reset your password via your registered email address.',
      },
      {
        id: 'contact_support',
        question: 'How can I contact support?',
        answer: 'You can reach our support team by emailing support@docmobile.com or by calling us at (123) 456-7890 during business hours (Mon-Fri, 9 AM - 5 PM).',
      },
    ],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    type: 'faq',
    data: [
      {
        id: 'app_crashing',
        question: 'My app keeps crashing. What should I do?',
        answer: 'Try restarting your device and ensuring your app is updated to the latest version. If the issue persists, please clear the app cache from your device settings or reinstall the app.',
      },
      {
        id: 'document_not_loading',
        question: 'Why is my document not loading?',
        answer: 'Check your internet connection. If you are connected, try refreshing the page. Large documents may take longer to load. If the problem continues, contact support.',
      },
    ],
  },
];